name: .NET Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: restore dotnet
        run: dotnet restore
        
      - name: build the solution
        run: msbuild UIElementsUnturned.sln
